### ISSUE TITLE
Keyboard input doesn't work well with non-US keyboard layouts

### ISSUE THREAD

**Issue by depp** [straker/kontra#112]
For example, if you write a game to use WASD and have a French keyboard layout, the input should accept ZQSD.

**Comment by burntcustard** [comment]
I've had a look through all the Kontra keyboard, and pull-request-ed-keyboard-code and... I think I disagree with all of it :laughing: 

It'd be much better size-wise to use separate functions, with `KeyboardEvent.key` for layout-specific key presses (e.g. `keyPressed()`), and `KeyboardEvent.code` for layout-independant key presses (e.g.`keyCodePressed()`), so that the person using Kontra can decide whichever they want to take up valuable bytes. Aaaaand dropping `KeyboardEvent.which` and the `keyMap` entirely.

I _believe_ for Edge and IE support, `.includes()` or `.indexOf()` could be used to check for the weirdnesses in the names of keys in those browsers, for `KeyboardEvent.key`s, e.g. because 'ArrowUp' is just 'Up' in Edge.

If there's interested I might make an alternate version like I've described?

**Comment by depp** [comment]
> It'd be much better size-wise to use separate functions, …

I’m a bit unclear on what’s being separated out. The PR fixes issues with non-US keyboard layouts by using layout-independent `.code`, and falls back to `.which` for compatibility with Edge. This fixes the immediate problem without forcing breaking API changes on downstream users.

I agree that long-term you would probably want to just use `.code` for WASD-style controls, and you can ditch `keyMap`—this might save some bytes, but is also a breaking API change. If you just wait a little while, the Edge compatibility problem will solve itself as Edge will be yet another flavor of Chrome.

I would be concerned that `keyCodePressed` and `keyPressed` is a bit of a footgun. Maybe `keyCharPressed` and `keyCodePressed`? With warnings that you don’t want to use both at the same time, because if you use both, you might bind different actions to the same key unintentionally.

**Comment by depp** [comment]
And just as a caveat—using `.key` is a bit of trouble, because you will get events like this:

```
keydown key='a'
keydown key='Shift'
keyup key='A'
```

You can solve this with `.toLowerCase()` but what about punctuation like `'.' / '>'`? Using `.key` for games can turn into a bit of a mess if you want to handle things like modifiers.

**Comment by burntcustard** [comment]
Yep, having both `.key` and `.code` available is a bit precarious, but I think people could understand the choice. The breaking-change point is a good one - I'd lean towards doing it sooner rather than later though, and from what I saw, there were literally dozens of us anti-`KeyboardEvent.which` folk participating in Js13k this year.

The bonus to splitting them is that Edge and/or IE support are easier with `.key` (without having to use a keymap for Edge) - and in some cases it might be the preferred property. E.g. in my Js13k game, I used `.key` because it ended up saving bytes over `.code`, and I didn't have any scary overlaps. Or e.g. in RTS games the modifiers can be really useful for things like shift+1 for unit selection, and it's (sometimes) easier to use `.key` for those.

**Comment by depp** [comment]
I think it might make sense for the `.key` version to be callback-only, since it’s somewhat complicated to detect `'keyup'`. This might make things clearer for users too.

**Comment by straker** [comment]
I'd prefer a single method of entry for keyboard input to make it both simpler and layout independent. Multiple functions that practically do the same thing would only cause confusion. I'd also prefer to not exclude modern browser(s) just to save a few bytes. If we're concerned with the size increase, I'm sure we could figure out a smaller size way of handling the fallback support. 

I'm also OK with a breaking change to handle `.code`, but I wouldn't merge it for a bit until I have other breaking changes ready as well (#105, removing collision from the sprite class and making it it's own set of functions, and some other things possibly).

**Comment by straker** [comment]
I'll make a note of the size issue for v7 and see if by the time i get to it Edge has updated with chromium engine.
