### ISSUE TITLE
TileEngine.renderLayer() does not rerender canvas after dirty

### ISSUE THREAD

**Issue by straker** [straker/kontra#116]
If you update the tileEngine layer data and then call `tileEngine.setLayer()`, the changes will not be applied as the function does not call `prerender()` if the tileEngine is dirty.

Essentially we just need to update [`tileEngine.renderLayer`](https://github.com/straker/kontra/blob/master/src/tileEngine.js#L186-L202) to call `prerender()` (`this._p()`) like [we did in the `render` function](https://github.com/straker/kontra/blob/master/src/tileEngine.js#L171-L173).

We should also [add a test to check that it calls `prerender` when dirty](https://github.com/straker/kontra/blob/master/test/unit/tileEngine.spec.js#L82-L106).

**Comment by reece-bennett** [comment]
I'm going to have a go at this issue.

Done a bit of playing around already, I'm a bit confused what the call to prerender actually does. Should it just help with performance or should there be a visual difference?

**Comment by straker** [comment]
Awesome! So the tile engine is drawn to an offscreen canvas, and every time render is called it just draws the offscreen canvas to the game canvas. This helps a ton with performance as we don't have to do all the calculations of drawing each individual tile of each layer every frame. Instead we just copy a static image to the main canvas every frame.

When a user changes a layer or tile, we need to update the offscreen canvas (calling `prerender`) so it redraws the entire tile map again for the next render.

**Comment by ajbkr** [comment]
@reece-bennett Perhaps this Twitter exchange might be of some use? https://twitter.com/ajbkr/status/1174403215850385412

**Comment by reece-bennett** [comment]
Thanks @ajbkr, gotten a bit closer with your tweets.

@straker I tried adding 
```javascript
if (this._d) {
  this._d = false;
  this._p();
}
```
to the start of 
https://github.com/straker/kontra/blob/362a51dbb06292b86e4d669be679819d3b27e378/src/tileEngine.js#L186-L199
but that doesn't seem to update the tiles on-screen if you are calling `tileEngine.renderLayer()` from the render loop.

Allowing the if statement at line 190 above to run if the tileEngine is dirty works, but then tests start failing because of `renderLayer` being called twice.

Any thoughts?
