### ISSUE TITLE
Support for pointers on `object.render()` objects

### ISSUE THREAD

**Issue by TheGreatRambler** [straker/kontra#16]
For objects that I have created with this function:
```
function createCircle(options) {
            var circleSprite = kontra.sprite({
                x: options.x,
                y: options.y,
                color: options.color,
                radius: options.radius,
                width: options.radius * 2,
                height: options.radius * 2,
                render: function() {
                    this.context.fillStyle = this.color;
                    this.context.beginPath();
                    this.context.arc(this.x, this.y, this.radius, 0, 2 * Math.PI);
                    this.context.fill();
                },
                onDown: function() {
                    console.log("Hello"); // never called
                },
                collidesWithPointer: function(pointer) {
                    // perform a circle v circle collision test
                    var dx = pointer.x - this.x;
                    var dy = pointer.y - this.y;
                    var isCollided = Math.sqrt(dx * dx + dy * dy) < this.radius;
                    return isCollided;
                }
            });
            return circleSprite;
        }
```
Simple circles; I have implemented the `collidesWithPointer()` method and I read in the API that `the object must haven been rendered to the canvas using object.render()`. I don't understand why this would be needed since I supplied a `collidesWithPointer()` method. All I ask is you remove this `object.render()` check and only check for a `collidesWithPointer()` method.

**Comment by straker** [comment]
Hello TheGreatRambler. Thanks for the suggestion.

So the requirement to render the object before I can check for collision with the pointer is so I know where the object is. If it hasn't been rendered to the canvas how can the user know where it is to click on it? It also allows me to know the order in which objects are rendered (since objects rendered last are on drawn on top). The `collidesWithPointer` function is just run once the user has clicked on the canvas to know if their click collided with a rendered object.

Is there a particular reason why you wouldn't render the object before the user clicked on it?

**Comment by TheGreatRambler** [comment]
The way I understand this, pointers only work for sprites that are rectangles (sprites without a `render()` method, but why cant sprites with special `render()` methods (like circles) be supported too? I'm not sure if we understand each other, but this is all I am wondering.

**Comment by straker** [comment]
Ah, I see. Sorry for the misunderstanding. 

Yes, any sprite or object can work with pointers. It doesn't have to be a rectangle. I should update the docs to make that more clear. 

There are two requirements to make any object work with the pointer: 

1. the object has to be tracked via `kontra.pointer.track(sprite)`
1. the object needs to be rendered using the sprites `render()` function. That function can be the default one or any custom one you pass it (like the circle). So long as `sprite.render()` is called, the pointer should work with it.

The optional requirement is using `collidesWithPointer()` to tell the pointer how it interacts with the sprite. A circular sprite will need it to run a circle vs. circle collision, just as you've done.

**Comment by TheGreatRambler** [comment]
For instancem, why not include a function like this?
```
kontra.canvas.onclick = function(event) {
    sprites.forEach(function(item) {
        if (item.collidesWithPointer({
                x: event.pageX - event.currentTarget.offsetLeft,
                y: event.pageY - event.currentTarget.offsetTop
            })) {
            item.onDown(event);
        }
    });
}
```

**Comment by straker** [comment]
You could totally do that if you want. That's essentially what `kontra.pointer` does when you click on the canvas.

The only tricky part is what happens when more than one sprite collides with the pointer? Which one did the player want to click? Do you fire the `onDown()` function for every one of them? Or do you just want one sprite to be clicked at a time?

**Comment by TheGreatRambler** [comment]
It seems to be somewhat inconsistent, so I'm going to stick with the function I put above. I will close this thread because this is only a small part of my program and I must be making an error on my part, but if someone gets it to work, feel free to open this thread back open.

**Comment by TheGreatRambler** [comment]
Referring to your question about when multiple collide, in my program, they (hopefully) will never collide, so I'm sticking with it.

**Comment by straker** [comment]
Sounds good. Good luck!
