### ISSUE TITLE
Idea: Community chat/forum?

### ISSUE THREAD

**Issue by Nezteb** [straker/kontra#368]
There doesn't seem to be a central place for talking about Kontra and gamedev in general. Some common options:

- Chat
  - [Discord](https://discord.com/)
  - [Matrix](https://matrix.org/) (with a client like [Element](https://element.io/))
    - [Gitter](https://gitter.im) now uses Matrix as well
  - [Zulip](https://zulip.com/)
  - [Linen](https://www.linen.dev/)
  - [IRC](https://libera.chat/)
  - [Discourse Chat](https://blog.discourse.org/2022/08/discourse-chat-is-now-available-try-it-out-today/)
    - Only if Discourse is chosen obviously
- Forum
  - [Discourse](https://www.discourse.org)
  - [Flarum](https://flarum.org)
  - [Talkyard](https://www.talkyard.io)
  - [GitHub Discussions](https://github.com/features/discussions)

Most other game engines/frameworks/libraries I follow use the combo of Discord + Discourse, but I wanted to list several options for each. 😄

**Comment by straker** [comment]
Thanks for the ideas. There are Kontra channels in both the JS13k slack and discord and Gamedev.js discord, but they get so little chat that I don't feel a great need to setup a dedicated Kontra discord or chat server (or maintain it). I wouldn't be opposed to setting up GitHub Discussions since it's built into the repo.

**Comment by Nezteb** [comment]
> There are Kontra channels in both the JS13k slack and discord and Gamedev.js discord

Oh I didn't even realize there were existing Slack/Discord channels! That makes sense, I'll go check those out!
