### ISSUE TITLE
iOS < 10 Safari - Unexpected Identifier 'imageRegex'

### ISSUE THREAD

**Issue by BoldBigflank** [straker/kontra#71]
v5.3.0
Trying to load kontrajs on an old ipod touch with iOS 9.3.5, but fails.

This is likely an ES6 issue. The message is:
Unexpected identifier 'imageRegex'

Not sure how much effort should go into fixing old devices, but it's something I'm seeing so I would love some help if possible.

**Comment by straker** [comment]
Hmm. I don't have an old iOS device myself, but based on the location of the error I want to say it's because the `let` right before `imageRegex`, which wasn't supported in until iOS 10. There quite a few modern syntax and features, like `WeakMap` and  `Promise`, which will cause problems in devices that don't support them.

I want to say the solution is to transpile and polyfill for older devices, especially now that v6.0.0 is fully ES6 syntax.

**Comment by straker** [comment]
Added note to Getting Starting page about ES6 support and to transpile and polyfill for older browsers.

**Comment by BoldBigflank** [comment]
Cool.
What I ended up doing was moving a copy of kontra.js into the project so it would be folded in and get transpiled with the rest of the project.
Transpiling for older devices might make the project file bigger, which goes against the goal of the project. It's still useful, so perhaps there can be an es5 version separate from the usual kontra.js and kontra.min.js files.
