### ISSUE TITLE
Viewport Control

### ISSUE THREAD

**Issue by BoldBigflank** [straker/kontra#81]
Another idea, not sure where this would fit in the system. It would be nice to set a viewport with an x, y, width and height. Every frame this would translate and scale the context before going through the `render` function. This would make it easy to zoom and focus on certain sprites in a larger-than-viewport-size map.

**Comment by straker** [comment]
I'm not sure I quite follow. Is the idea similar to what TileMap does with its `sx` and `sy` properties for larger maps?

**Comment by Rayne** [comment]
If I understand the request correctly, it would add an option to zoom in and out of the map by defining a custom viewport width and height.

**Comment by straker** [comment]
Would setting `ctx.scale` before drawing work? 

The main problem is that only the TileEngine is set up with a "camera" setting to handle larger maps (and it's just there to tell it where to start drawing the map), but there isn't anything in the rest of the library that understands that since most of the time the library has you do everything (like when to draw things and in what order). Having a system that understands camera, viewport, and scale would need to communicate that info to every sprite and tilemap.

As such, I'm not sure it fits in the system as it would require too much interdependency. You could try making it a plugin though, or maybe a sub-system that can work with Kontra.

**Comment by straker** [comment]
So with the most recent update to the library, Sprites now understand camera positions using `sx` and `sy`. You can [add objects to the tile engine](https://straker.github.io/kontra/api/tileEngine#adding-objects-to-the-tilemap) and it will sync the camera position to to the sprite so the sprite will draw itself in the correct spot even while the camera moves.

This now opens the door for viewport control as moving all the sprites would be just a matter of setting all their `sx` and `sy` positions.

**Comment by straker** [comment]
Closed via #169
